# Generated by Django 3.1.7 on 2021-03-24 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210324_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='listing',
            new_name='property_name',
        ),
    ]
