# Generated by Django 3.1.7 on 2021-03-22 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 22, 15, 39, 12, 146421, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='listing',
            table='listings',
        ),
        migrations.AlterModelTable(
            name='listingphoto',
            table='listing_photos',
        ),
    ]
