# Generated by Django 3.1.7 on 2021-03-23 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20210323_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 23, 2, 44, 2, 942134, tzinfo=utc)),
        ),
    ]
