# Generated by Django 3.1.7 on 2021-03-23 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_auto_20210323_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
